CREATE OR REPLACE VIEW WATSON.V_SCHD_SHIFT_XREF
AS
    ( SELECT SS.PLANT_CODE
           , SS.SHIFT_ID
           , SS.SHIFT_NAME
           , SS.SHIFT_DESC
           , FS.SHIFT_ID     LEGACY_SHIFT_ID
       FROM WATSON.SCHD_SHIFT SS, WATSON.FILL_SHIFTS@WATSONP.WORLD FS
      WHERE SS.PLANT_CODE = FS.PLANT_CODE AND SS.SHIFT_NAME = FS.SHIFT_NAME );
