WHENEVER SQLERROR CONTINUE;

DROP INDEX SCHD_CAL_BREAK_SETUP_U01;

CREATE UNIQUE INDEX SCHD_CAL_BREAK_SETUP_U01 ON WATSON.SCHD_CAL_BREAK_SETUP ( PLANT_CODE, AREA_ID, SHIFT_ID, TEAM_ID, ROTATION_FLAG, ROTATION_DAY, START_DT, END_DT);
