WHENEVER SQLERROR CONTINUE;

DROP INDEX schd_cal_break_U01;

CREATE UNIQUE INDEX schd_cal_break_U01 ON WATSON.schd_cal_break( PLANT_CODE, AREA_ID, SHIFT_ID, TEAM_ID, ROTATION_FLAG, ROTATION_DAY, START_DT, END_DT);
 